storage_dir: "storage/" # Path to the directory where heavy duty storage will be done, meant for large files like models and datasets. Change this value to store output files in a different location.
OPENAI_API_KEY: "PUT_YOUR_OPENAI_API_KEY_HERE"
ANTHROPIC_API_KEY: "PUT YOUR ANTHROPIC_API_KEY_HERE"